useDebugBar: '%env(USE_DEBUGBAR)%'
enableLogging: '%env(ENABLE_LOGGING)%'
logFileName: 'app.log'
logOnlyInDebugBar: '%env(USE_DEBUGBAR)%'

adminUrl: '/admin/'

templateName: 'main'
adminTemplateName: 'admin'
twigDebug: '%env(DEBUG_MODE)%'
twigUseCache: false
twigAutoReload: 'true'

debugMode: '%env(DEBUG_MODE)%'