10: '\App\Services\EventDispatcherServiceProvider'
20: '\App\Services\LoggerServiceProvider'
30: '\App\Services\EventListenersServiceProvider'
40: '\App\Services\FlashServiceProvider'
50: '\App\Services\ValidatorServiceProvider'
60: '\App\Services\DatabaseServiceProvider'
70: '\App\Services\TwigServiceProvider'
80: '\App\Services\MailServiceProvider'
90: '\App\Services\ControllerFactoryServiceProvider'
100: '\App\Services\DebugBarServiceProvider'
110: '\App\Services\RouteControllersServiceProvider'