displayErrorDetails: '%env(DISPLAY_ERROR_DETAILS)%'
addContentLengthHeader: false
determineRouteBeforeAppMiddleware: true
outputBuffering: false
routerCacheFile: false
displayErrorDetails: '%env(DEBUG_MODE)%'